
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module CONTROL_ENTRADAS(

	//////////// CLOCK //////////
	CLOCK_50,
	B_Left,
	B_Right,
	B_Up,
	B_Down,
	B_Start,
	B_RESET,
	LEFT,
	RIGHT,
	UP,
	DOWN,
	START,
	RESET
	
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================
 
input 	CLOCK_50;
input    B_RESET;
input		B_Left;
input 	B_Right;
input		B_Up;
input		B_Down;
input    B_Start;

output	wire LEFT;
output	wire RIGHT;
output	wire UP;
output	wire DOWN;
output	wire START;
output	wire RESET;


//=======================================================
//  REG/WIRE declarations
//=======================================================

wire  Left_w;
wire	Right_w;
wire	Up_w;
wire	Down_w;
wire	Start_w;
wire	RESET_W;

//=======================================================
//  Structural coding
//=======================================================	
DeBounce DeBounce_1 (
// port map - connection between master ports and signals/registers   
	.D_CLOCK_50(CLOCK_50),
	.D_Reset(RESET_W),
	.D_Button_In(~B_Left),
	.D_Button_Out(Left_w)
);
DeBounce DeBounce_2 (
// port map - connection between master ports and signals/registers   
	.D_CLOCK_50(CLOCK_50),
	.D_Reset(RESET_W),
	.D_Button_In(~B_Right),
	.D_Button_Out(Right_w)
);
DeBounce DeBounce_3 (
// port map - connection between master ports and signals/registers   
	.D_CLOCK_50(CLOCK_50),
	.D_Reset(RESET_W),
	.D_Button_In(~B_Up),
	.D_Button_Out(Up_w)
);
DeBounce DeBounce_4 (
// port map - connection between master ports and signals/registers   
	.D_CLOCK_50(CLOCK_50),
	.D_Reset(RESET_W),
	.D_Button_In(~B_Down),
	.D_Button_Out(Down_w)
);
DeBounce DeBounce_5 (
// port map - connection between master ports and signals/registers   
	.D_CLOCK_50(CLOCK_50),
	.D_Reset(RESET_W),
	.D_Button_In(B_Start),
	.D_Button_Out(Start_w)
);

FILTRO FILTRO_0(
	.F_CLOCK_50(CLOCK_50),
	.F_RESET(RESET_W),
	.F_OUT(LEFT),
	.F_IN(Left_w)
);	

FILTRO FILTRO_1(
	.F_CLOCK_50(CLOCK_50),
	.F_RESET(RESET_W),
	.F_OUT(RIGHT),
	.F_IN(Right_w)
);

FILTRO FILTRO_2(
	.F_CLOCK_50(CLOCK_50),
	.F_RESET(RESET_W),
	.F_OUT(UP),
	.F_IN(Up_w)
);

FILTRO FILTRO_3(
	.F_CLOCK_50(CLOCK_50),
	.F_RESET(RESET_W),
	.F_OUT(DOWN),
	.F_IN(Down_w)
);

FILTRO FILTRO_4(
	.F_CLOCK_50(CLOCK_50),
	.F_RESET(RESET_W),
	.F_OUT(START),
	.F_IN(Start_w)
);

DeBounce DeBounce_0 (
// port map - connection between master ports and signals/registers   
	.D_CLOCK_50(CLOCK_50),
	.D_Reset(1'b0),
	.D_Button_In(~B_RESET),
	.D_Button_Out(RESET_W)
);

assign RESET= RESET_W;

endmodule
