
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module System(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////
	
	MAX7219_DIN,
	MAX7219_CS,
	MAX7219_CLK,
	B_Left,
	B_Right,
	B_Up,
	B_Down,
	B_Start,
	RESET
	
	
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 	CLOCK_50;
input    RESET;
input		B_Left;
input 	B_Right;
input		B_Up;
input		B_Down;
input    B_Start;


//////////// LED //////////
output	[7:0]		LED;

//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////

output   MAX7219_DIN;
output	MAX7219_CS;
output	MAX7219_CLK;

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [7:0] fila0;
wire [7:0] fila1;
wire [7:0] fila2;
wire [7:0] fila3;
wire [7:0] fila4;
wire [7:0] fila5;
wire [7:0] fila6;
wire [7:0] fila7;

wire LEFT_W;
wire RIGHT_W;
wire UP_W;
wire DOWN_W;
wire START_W;
wire RESET_S;
//=======================================================
//  Structural coding
//=======================================================
CONTROL_ENTRADAS CONTROL_ENTRADAS_U0(
	.CLOCK_50(CLOCK_50),
	.B_Left(B_Left),
	.B_Right(B_Right),
	.B_Up(B_Up),
	.B_Down(B_Down),
	.B_Start(B_Start),
	.B_RESET(RESET),
	.LEFT(LEFT_W),
	.RIGHT(RIGHT_W),
	.UP(UP_W),
	.DOWN(DOWN_W),
	.START(START_W),
	.RESET(RESET_S)
);

JUEGO JUEGO_u0 (
   .JUEGO_7_OUT(fila7),
   .JUEGO_6_OUT(fila6),
	.JUEGO_5_OUT(fila5),
	.JUEGO_4_OUT(fila4),
	.JUEGO_3_OUT(fila3),
	.JUEGO_2_OUT(fila2),
	.JUEGO_1_OUT(fila1),
	.JUEGO_0_OUT(fila0), 
	.JUEGO_CLOCK(CLOCK_50),
	.JUEGO_RESET(RESET_S),	
	.JUEGO_START(START_W),
	.JUEGO_LEFT(LEFT_W),
	.JUEGO_RIGHT(RIGHT_W),
	.JUEGO_UP(UP_W),
	.JUEGO_DOWN(DOWN_W)
);

control_matriz control_matriz_u0(
	.CLOCK_50(CLOCK_50),
	.RESET(RESET_S),
	.fila0(fila0),
	.fila1(fila1),
	.fila2(fila2),
	.fila3(fila3),
	.fila4(fila4),	
	.fila5(fila5),
	.fila6(fila6),
	.fila7(fila7),
	.MAX7219_DIN(MAX7219_DIN),
	.MAX7219_CS(MAX7219_CS),
	.MAX7219_CLK(MAX7219_CLK)
);

assign LED[0] = B_Left; // Button Left
assign LED[1] = B_Right;// Button Right
assign LED[2] = B_Up;	// Button Down
assign LED[3] = B_Down;	// Button Up
assign LED[6] = RESET_S;
assign LED[7] = B_Start;	// Button Start

endmodule
