
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module System(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////
	
	MAX7219_DIN,
	MAX7219_CS,
	MAX7219_CLK,
	B_Left,
	B_Right,
	B_Up,
	B_Down,
	B_Start,
	RESET,
	
	led_final_7_tester,
	led_final_6_tester,
	led_final_5_tester,
	led_final_4_tester,
	led_final_3_tester,
	led_final_2_tester,
	led_final_1_tester,
	led_final_0_tester
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 	CLOCK_50;
input    RESET;
input		B_Left;
input 	B_Right;
input		B_Up;
input		B_Down;
input    B_Start;


//////////// LED //////////
output	[7:0]		LED;

//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////

output   MAX7219_DIN;
output	MAX7219_CS;
output	MAX7219_CLK;

output [7:0] led_final_7_tester;
output [7:0] led_final_6_tester;
output [7:0] led_final_5_tester;
output [7:0] led_final_4_tester;
output [7:0] led_final_3_tester;
output [7:0] led_final_2_tester;
output [7:0] led_final_1_tester;
output [7:0] led_final_0_tester;

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [7:0] fila0;
wire [7:0] fila1;
wire [7:0] fila2;
wire [7:0] fila3;
wire [7:0] fila4;
wire [7:0] fila5;
wire [7:0] fila6;
wire [7:0] fila7;

wire B_Left;
wire B_Right;
wire B_Up;
wire B_Down;
wire B_Start;
wire RESET;
//=======================================================
//  Structural coding
//=======================================================

JUEGO JUEGO_u0 (
   .JUEGO_7_OUT(fila7),
   .JUEGO_6_OUT(fila6),
	.JUEGO_5_OUT(fila5),
	.JUEGO_4_OUT(fila4),
	.JUEGO_3_OUT(fila3),
	.JUEGO_2_OUT(fila2),
	.JUEGO_1_OUT(fila1),
	.JUEGO_0_OUT(fila0), 
	.JUEGO_CLOCK(CLOCK_50),
	.JUEGO_RESET(RESET),	
	.JUEGO_START(B_Start),
	.JUEGO_LEFT(B_Right),
	.JUEGO_RIGHT(B_Left),
	.JUEGO_UP(B_Up),
	.JUEGO_DOWN(B_Down)
);

control_matriz control_matriz_u0(
	.CLOCK_50(CLOCK_50),
	.RESET(RESET),
	.fila0(fila0),
	.fila1(fila1),
	.fila2(fila2),
	.fila3(fila3),
	.fila4(fila4),	
	.fila5(fila5),
	.fila6(fila6),
	.fila7(fila7),
	.MAX7219_DIN(MAX7219_DIN),
	.MAX7219_CS(MAX7219_CS),
	.MAX7219_CLK(MAX7219_CLK)
);

assign LED[0] = B_Left; // Button Left
assign LED[1] = B_Right;// Button Right
assign LED[2] = B_Up;	// Button Down
assign LED[3] = B_Down;	// Button Up
assign LED[6] = RESET;
assign LED[7] = B_Start;	// Button Start

assign led_final_7_tester = fila7;
assign led_final_6_tester = fila6;
assign led_final_5_tester = fila5;
assign led_final_4_tester = fila4;
assign led_final_3_tester = fila3;
assign led_final_2_tester = fila2;
assign led_final_1_tester = fila1;
assign led_final_0_tester = fila0;

endmodule
