
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module system(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////
	
	MAX7219_DIN,
	MAX7219_CS,
	MAX7219_CLK,
	B_Left,
	B_Rigth,
	B_Up,
	B_Down,
	Start,
	RESET,
	
	led_final_7_tester,
	led_final_6_tester,
	led_final_5_tester,
	led_final_4_tester,
	led_final_3_tester,
	led_final_2_tester,
	led_final_1_tester,
	led_final_0_tester
	
	
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 	CLOCK_50;
input    RESET;
input		B_Left;
input 	B_Rigth;
input		B_Up;
input		B_Down;
input    Start;


//////////// LED //////////
output	[7:0]		LED;

//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////

output   MAX7219_DIN;
output	MAX7219_CS;
output	MAX7219_CLK;

output [7:0] led_final_7_tester;
output [7:0] led_final_6_tester;
output [7:0] led_final_5_tester;
output [7:0] led_final_4_tester;
output [7:0] led_final_3_tester;
output [7:0] led_final_2_tester;
output [7:0] led_final_1_tester;
output [7:0] led_final_0_tester;

parameter NOT_8 = 8'b00000000;
parameter NOT_3 = 8'b111;

//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [7:0] data_max;
wire [2:0] add;

wire [7:0] led_final_7_patch;
wire [7:0] led_final_6_patch;
wire [7:0] led_final_5_patch;
wire [7:0] led_final_4_patch;
wire [7:0] led_final_3_patch;
wire [7:0] led_final_2_patch;
wire [7:0] led_final_1_patch;
wire [7:0] led_final_0_patch;

wire [7:0] rana_final_7_patch;
wire [7:0] rana_final_6_patch;
wire [7:0] rana_final_5_patch;
wire [7:0] rana_final_4_patch;
wire [7:0] rana_final_3_patch;
wire [7:0] rana_final_2_patch;
wire [7:0] rana_final_1_patch;
wire [7:0] rana_final_0_patch;

wire [7:0] vehiculo_final_6_patch;
wire [7:0] vehiculo_final_5_patch;
wire [7:0] vehiculo_final_4_patch;
wire [7:0] vehiculo_final_3_patch;
wire [7:0] vehiculo_final_2_patch;
wire [7:0] vehiculo_final_1_patch;

wire [2:0] estado_sistema_patch;
wire [1:0] nivel_sistema_patch;

wire left_final_patch;
wire right_final_patch;
wire up_final_patch;
wire down_final_patch;
wire rana_ini_patch;


//=======================================================
//  Structural coding
//=======================================================
	matrix_ctrl matrix_ctrl_unit_0(    // Driver MAX7219
		.max7219_din(MAX7219_DIN),//max7219_din 
		.max7219_ncs(MAX7219_CS),//max7219_ncs 
		.max7219_clk(MAX7219_CLK),//max7219_clk
		.disp_data(data_max), 
		.disp_addr(add),
		.intensity(4'hA),
		.clk(CLOCK_50),
		.reset(~RESET) //~lowRst_System
	 );
	 
	imagen imagen_1(  // Load Image
		.act_add(add), 
		.max_in(data_max),
		.led_final_7_in(led_final_7_patch),
		.led_final_6_in(led_final_6_patch),
		.led_final_5_in(led_final_5_patch),
		.led_final_4_in(led_final_4_patch),
		.led_final_3_in(led_final_3_patch),
		.led_final_2_in(led_final_2_patch),
		.led_final_1_in(led_final_1_patch),
		.led_final_0_in(led_final_0_patch)
	);
	
	PINTAR_MATRIZ PINTAR_MATRIZ_T1(
	.PINTAR_7_OUT(led_final_7_patch),
	.PINTAR_6_OUT(led_final_6_patch),
	.PINTAR_5_OUT(led_final_5_patch),
	.PINTAR_4_OUT(led_final_4_patch),
	.PINTAR_3_OUT(led_final_3_patch),
	.PINTAR_2_OUT(led_final_2_patch),
	.PINTAR_1_OUT(led_final_1_patch),
	.PINTAR_0_OUT(led_final_0_patch),
//////////// INPUTS //////////
	.PINTAR_RANA_7_IN(rana_final_7_patch),
	.PINTAR_RANA_6_IN(rana_final_6_patch),
	.PINTAR_RANA_5_IN(rana_final_5_patch),
	.PINTAR_RANA_4_IN(rana_final_4_patch),
	.PINTAR_RANA_3_IN(rana_final_3_patch),
	.PINTAR_RANA_2_IN(rana_final_2_patch),
	.PINTAR_RANA_1_IN(rana_final_1_patch),
	.PINTAR_RANA_0_IN(rana_final_0_patch),
	
	.PINTAR_VEHICULOS_6_IN(NOT_8),
	.PINTAR_VEHICULOS_5_IN(NOT_8),
	.PINTAR_VEHICULOS_4_IN(NOT_8),
	.PINTAR_VEHICULOS_3_IN(NOT_8),
	.PINTAR_VEHICULOS_2_IN(NOT_8),
	.PINTAR_VEHICULOS_1_IN(NOT_8),
	
	.PINTAR_MENU_PRINCIPAL_ESTADO_IN(NOT_3),
	.PINTAR_CLOCK(CLOCK_50),
	.PINTAR_RESET(~RESET)
	);
	
	rebote rebote_1(
    .clk(CLOCK_50), .reset(~RESET),
    .sw(B_Up),
    .db_level(), .db_tick(up_final_patch)
    );

rebote rebote_2(
    .clk(CLOCK_50), .reset(~RESET),
    .sw(B_Down),
    .db_level(), .db_tick(down_final_patch)
    );

rebote rebote_3(
    .clk(CLOCK_50), .reset(~RESET),
    .sw(B_Left),
    .db_level(), .db_tick(left_final_patch)
    );

rebote rebote_4(
    .clk(CLOCK_50), .reset(~RESET),
    .sw(B_Right),
    .db_level(), .db_tick(right_final_patch)
);
	
	RANA rana_1(
    .RANA_7_OUT(rana_final_7_patch),
	 .RANA_6_OUT(rana_final_6_patch),
	 .RANA_5_OUT(rana_final_5_patch),
	 .RANA_4_OUT(rana_final_4_patch),
	 .RANA_3_OUT(rana_final_3_patch),
	 .RANA_2_OUT(rana_final_2_patch),
	 .RANA_1_OUT(rana_final_1_patch),
	 .RANA_0_OUT(rana_final_0_patch),
	 .RANA_CLOCK(CLOCK_50),
	 .RANA_RESET(~RESET),
	 .RANA_INI(rana_ini_patch),
	 .RANA_LEFT(left_final_patch),
	 .RANA_RIGHT(right_final_patch),
	 .RANA_UP(up_final_patch),
	 .RANA_DOWN(down_final_patch)
);

/**
	CONTROL_RANAS(
//////////// OUTPUTS //////////
	CR_GANO_JC_OUT,
	CR_PERDIO_JC_OUT,
	CR_RANA_INI_OUT(rana_ini_patch),
//////////// INPUTS //////////
	CR_GANO,
	CR_PERDIO,
	CR_ESTADO,
	CR_CLOCK_50,
	CR_RESET
);

	MENU_PRINCIPAL(
//////////// OUTPUTS //////////
	MP_ESTADO_OUT,
	MP_NVL_OUT,
	MP_CN_OUT,
//////////// INPUTS //////////
	MP_GANO,
	MP_PERDIO,
	MP_DOWN,
	MP_UP,
	MP_START,
	MP_CLOCK_50,
	MP_RESET
);

	NIVEL_VEHICULOS (
//////////// OUTPUTS //////////
	NVE_REG_5_OUT,
	NVE_REG_4_OUT,
	NVE_REG_3_OUT,
	NVE_REG_2_OUT,
	NVE_REG_1_OUT,
	NVE_REG_0_OUT,
//////////// INPUTS //////////
	NVE_CLOCK,
	NVE_RESET,
	NVE_ESTADO_IN,
	NVE_NV_IN,
	NVE_CN_IN
);
*/

assign LED[0] = B_Left; // Button Left
assign LED[1] = B_Rigth;// Button Right
assign LED[2] = B_Up;	// Button Down
assign LED[3] = B_Down;	// Button Up
assign LED[7] = Start;	// Button Start

assign led_final_7_tester = led_final_7_patch;
assign led_final_6_tester = led_final_6_patch;
assign led_final_5_tester = led_final_5_patch;
assign led_final_4_tester = led_final_4_patch;
assign led_final_3_tester = led_final_3_patch;
assign led_final_2_tester = led_final_2_patch;
assign led_final_1_tester = led_final_1_patch;
assign led_final_0_tester = led_final_0_patch;

endmodule
